version: "3.9"
services:
  app:
    image: bank-app:latest
    build:
      context: .
    ports:
      - "8081:8081"
    depends_on:
      - postgres
    environment:
      SPRING_PROFILES_ACTIVE: prod
      PGHOST: postgres
      PGPORT: 5432
      PGDATABASE: bank
      PGUSER: postgres
      PGPASSWORD: root

  postgres:
    image: postgres:15
    container_name: postgres-container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: bank
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: