spring:
  datasource:
      url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
      username: ${PGUSER}
      password: ${PGPASSWORD}
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8081

logging:
  level:
    org.hibernate: DEBUG