spring:
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: false
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: test
    password: test
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8081

logging:
  level:
    org.hibernate: DEBUG